# OTB_Pipeline -- Oracle fix script (run once from the laptop)
# Fixes issues since moving from laptop to Oracle:
#   1. API keys blank   -> writes keys.env to Oracle from BHP config
#   2. Fonts missing    -> SCPs assets/fonts/ from BootHopPipeline to Oracle
#   3. No slot crons    -> adds pipeline.py crons for all 4 slots
#   4. Dedup logs reset -> fixes git-pull cron to code-only (stops overwriting query_log.json)
#
# Usage (from OTB_Pipeline directory):
#   .\deploy\fix_oracle.ps1

param(
    [string]$OracleIP   = "140.238.73.32",
    [string]$KeyFile    = "$env:USERPROFILE\.ssh\oracle_boothop.pem",
    [string]$OracleUser = "ubuntu",
    [string]$RemotePath = "/opt/otb_pipeline",
    [string]$BHPRoot    = "$env:USERPROFILE\Desktop\BootHopPipeline"
)

$ORACLE = "${OracleUser}@${OracleIP}"

function SSH-Run { param([string]$Cmd)
    Write-Host "[Oracle] $Cmd" -ForegroundColor Yellow
    & ssh -i "$KeyFile" -o StrictHostKeyChecking=no "$ORACLE" "$Cmd"
}

function SCP-Up { param([string]$Local, [string]$Remote)
    & scp -i "$KeyFile" -o StrictHostKeyChecking=no -r "$Local" "${ORACLE}:${Remote}"
}

Write-Host ""
Write-Host "=== OTB_Pipeline Oracle Fix ===" -ForegroundColor Cyan
Write-Host "Oracle: $ORACLE"
Write-Host ""

# -- Step 1: Extract API keys from BootHopPipeline config.py ------------------
Write-Host "Step 1: Reading API keys from BootHopPipeline..." -ForegroundColor Cyan

$bhpConfig = Join-Path $BHPRoot "config.py"
if (-not (Test-Path $bhpConfig)) {
    Write-Host "  ERROR: BHP config not found at $bhpConfig" -ForegroundColor Red
    Write-Host "  Update the -BHPRoot parameter if your path is different."
    exit 1
}

$escaped = $bhpConfig -replace '\\', '\\\\'
$keysScript = @"
import importlib.util
spec = importlib.util.spec_from_file_location('cfg', r'$escaped')
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m)
print('ANTHROPIC_API_KEY=' + getattr(m,'ANTHROPIC_API_KEY',''))
print('PEXELS_KEY=' + (getattr(m,'PEXELS_API_KEY','') or getattr(m,'PEXELS_KEY','')))
print('PIXABAY_KEY=' + getattr(m,'PIXABAY_KEY',''))
print('GEMINI_API_KEY=' + getattr(m,'GEMINI_API_KEY',''))
print('YOUTUBE_API_KEY=' + getattr(m,'YOUTUBE_API_KEY',''))
print('OPENAI_API_KEY=' + getattr(m,'OPENAI_API_KEY',''))
print('PERPLEXITY_KEY=' + getattr(m,'PERPLEXITY_KEY',''))
"@

$keyLines = & python -c $keysScript 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ERROR reading BHP config: $keyLines" -ForegroundColor Red
    exit 1
}

# Write local keys.env (excluded from git by .gitignore)
$keysEnvPath = "$PSScriptRoot\..\keys.env"
"# OTB_Pipeline API keys - generated by fix_oracle.ps1 - DO NOT COMMIT" | Out-File -FilePath $keysEnvPath -Encoding utf8
$keyLines | Out-File -FilePath $keysEnvPath -Encoding utf8 -Append
Write-Host "  OK  keys.env written locally" -ForegroundColor Green

SSH-Run "mkdir -p $RemotePath"
SCP-Up "$keysEnvPath" "$RemotePath/keys.env"
if ($?) {
    Write-Host "  OK  keys.env on Oracle" -ForegroundColor Green
} else {
    Write-Host "  WARN keys.env upload failed - check SSH connection" -ForegroundColor Yellow
}

# -- Step 2: Upload fonts to Oracle -------------------------------------------
Write-Host ""
Write-Host "Step 2: Uploading fonts..." -ForegroundColor Cyan

$fontsDir = Join-Path $BHPRoot "assets\fonts"
if (Test-Path $fontsDir) {
    SSH-Run "mkdir -p $RemotePath/assets/fonts"
    SCP-Up "$fontsDir\*" "$RemotePath/assets/fonts/"
    if ($?) {
        Write-Host "  OK  Fonts uploaded" -ForegroundColor Green
    } else {
        Write-Host "  WARN Font upload failed (render may use fallback fonts)" -ForegroundColor Yellow
    }
} else {
    Write-Host "  SKIP fonts folder not found at $fontsDir" -ForegroundColor Gray
}

# -- Step 3: Upload logo and end-card assets ----------------------------------
Write-Host ""
Write-Host "Step 3: Uploading pipeline assets..." -ForegroundColor Cyan

$assetsDir = Join-Path $BHPRoot "assets"
SSH-Run "mkdir -p $RemotePath/assets"
foreach ($asset in @("mainlogo.png", "FIG4End.png")) {
    $assetPath = Join-Path $assetsDir $asset
    if (Test-Path $assetPath) {
        SCP-Up "$assetPath" "$RemotePath/assets/$asset"
        if ($?) { Write-Host "  OK  $asset" -ForegroundColor Green }
    } else {
        Write-Host "  --  $asset not found (skipping)" -ForegroundColor Gray
    }
}

# -- Step 4: Create companies directory for Revoice Studio --------------------
Write-Host ""
Write-Host "Step 4: Creating Revoice Studio companies directory..." -ForegroundColor Cyan
SSH-Run "mkdir -p $RemotePath/dashboard/companies/boothop"
if ($?) { Write-Host "  OK  companies/boothop created" -ForegroundColor Green }

# -- Step 5: Push current data files to Oracle --------------------------------
Write-Host ""
Write-Host "Step 5: Pushing data files to Oracle (protects dedup logs)..." -ForegroundColor Cyan

$dataScript = "$PSScriptRoot\sync_data.ps1"
if (Test-Path $dataScript) {
    & "$dataScript" -OracleIP "$OracleIP" -KeyFile "$KeyFile" -OracleUser "$OracleUser" -Direction "push"
} else {
    Write-Host "  SKIP sync_data.ps1 not found" -ForegroundColor Gray
}

# -- Step 6: Fix crons on Oracle ----------------------------------------------
Write-Host ""
Write-Host "Step 6: Adding pipeline slot crons + fixing git sync cron..." -ForegroundColor Cyan

# The original cron used 'git pull origin main' which overwrote query_log.json every 5 min
# causing repeated video content. Fixed: selective checkout of code files only.
$gitSync  = "*/5 * * * * cd $RemotePath && git fetch origin main 2>/dev/null && git checkout origin/main -- pipeline.py config.py scripts/ deploy/ dashboard/ requirements.txt 2>/dev/null"
$slot1    = "0 7 * * * . $RemotePath/keys.env && cd $RemotePath && python3 pipeline.py --slot 1 >> /var/log/otb_slot1.log 2>&1"
$slot2    = "0 12 * * * . $RemotePath/keys.env && cd $RemotePath && python3 pipeline.py --slot 2 >> /var/log/otb_slot2.log 2>&1"
$slot3    = "30 17 * * * . $RemotePath/keys.env && cd $RemotePath && python3 pipeline.py --slot 3 >> /var/log/otb_slot3.log 2>&1"
$slot4    = "30 20 * * * . $RemotePath/keys.env && cd $RemotePath && python3 pipeline.py --slot 4 >> /var/log/otb_slot4.log 2>&1"

# Build new crontab: strip old OTB entries, add fresh block
$stripCmd = "crontab -l 2>/dev/null | grep -v 'pipeline.py' | grep -v 'git pull origin main' | grep -v 'git fetch origin main'"
$newCron  = "$gitSync\n$slot1\n$slot2\n$slot3\n$slot4"
SSH-Run "($stripCmd; printf '$newCron\n') | crontab -"

Write-Host "  OK  Git sync fixed (code-only, no data overwrite)" -ForegroundColor Green
Write-Host "  OK  Slot crons: 7:00, 12:00, 17:30, 20:30" -ForegroundColor Green

# Verify crons
SSH-Run "crontab -l"

# -- Step 7: Restart Telegram Commander ---------------------------------------
Write-Host ""
Write-Host "Step 7: Restarting Telegram Commander..." -ForegroundColor Cyan
SSH-Run "sudo systemctl restart otb-commander"
SSH-Run "sudo systemctl status otb-commander --no-pager -l"

# -- Done ---------------------------------------------------------------------
Write-Host ""
Write-Host "=== Oracle fix complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Now push the code changes so Oracle picks them up:" -ForegroundColor Cyan
Write-Host '  git add deploy/fix_oracle.ps1 pipeline.py config.py dashboard/main.py "dashboard/templates/dashboard.html" scripts/telegram_commander.py .gitignore' -ForegroundColor White
Write-Host '  git commit -m "fix: pipeline crons, video routing, platform labels, dedup protection"' -ForegroundColor White
Write-Host "  git push origin main" -ForegroundColor White
Write-Host ""
Write-Host "Oracle pulls code changes automatically within 5 minutes." -ForegroundColor Gray
Write-Host ""
Write-Host "Telegram fallback:  /rerun 3" -ForegroundColor Gray
Write-Host "Laptop SSH fallback:" -ForegroundColor Gray
Write-Host "  ssh -i $KeyFile ${OracleUser}@${OracleIP}" -ForegroundColor White
Write-Host "  Then: python3 $RemotePath/pipeline.py --slot 3 --force" -ForegroundColor White
